### ISSUE TITLE
Funcionalidad  para hacer la ventana3.py que muestre los usuarios registrados de forma tabular

### ISSUE THREAD

**Issue by Santipy1204** [Santipy1204/Clase9#16]
Usar el QWidget QTableWidget para mostrar los usuarios en forma de tabla y poner en esa ventana un botón para volver a la ventana2.py, la ventana de los items de los usuarios

**Comment by Santipy1204** [comment]
Por favor, trabajar en este nuevo issue mientras se revisa el issue #13

**Comment by Jonathanrivillas** [comment]
Listo ya hice el merge con las funcionalidades de items de usuarios y tablas de usuarios
